name: Terraform Plan Deployment AWS infrastructure

on:
  pull_request:

#Se van a crear los Jobs#

jobs:

  plan:
  runs-on: ubuntu-latest

#Se crean los steps#
  steps:
    uses: actions/checkout@v3

  #Ahora si vamos a correr los comandos de terraform (run)#
    name: plan-terraform-AWS-infra
    run: terraform plan

